### PR TITLE
Updated client up to 01172020

### PR DESCRIPTION
**Pull request by hsong-rh**
https://projects.engineering.redhat.com/browse/SSP-1134

### CODE REVIEW

**Review by mkanoor — APPROVED** [review]

**Review by syncrou — APPROVED** [review]

**Review by syncrou — CHANGES_REQUESTED** [review]
We should start pushing tags for these changes and simultaneously no longer use master (e.g. like catalog is for approval. )

**Comment by mkanoor** [comment]
@syncrou what should the format for the tags be?
v1.0
1.0

**Comment by syncrou** [comment]
Topo uses v1.0.0, v2.0.0 https://github.com/RedHatInsights/topological_inventory-api-client-ruby/tree/v2.0.0

**Review by syncrou — APPROVED** [review]
This LGTM 👍 We will follow up on the tagging changes in a new PR

**Pull request merged**
